import { createFileRoute, Link } from "@tanstack/react-router";
import { Building2, CheckCircle2, Clock3, Plus, Star } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/helpdesk/app-shell";
import { Field, Panel, SectionHeading, Stat } from "@/components/helpdesk/ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { branches } from "@/lib/helpdesk-data";
export const Route = createFileRoute("/branches")({ head: () => ({ meta: [{ title: "الفروع | وزير الحلو" }, { name: "description", content: "إنشاء ومتابعة بلاغات الفروع." }, { property: "og:title", content: "الفروع | وزير الحلو" }, { property: "og:description", content: "إنشاء ومتابعة بلاغات الفروع." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: BranchesPage });
function BranchesPage() { const [sent, setSent] = useState(false); return <AppShell title="لوحة الفرع"><SectionHeading title="الفروع وطلبات الدعم" description="أنشئ بلاغاً جديداً أو افتح لوحة أي فرع" /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="إجمالي الفروع" value="18" icon={Building2} /><Stat label="بلاغات مفتوحة" value="10" icon={Clock3} /><Stat label="مغلقة هذا الشهر" value="148" icon={CheckCircle2} /><Stat label="متوسط الرضا" value="4.8/5" icon={Star} /></section><section className="grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><Panel title="إنشاء بلاغ جديد" icon={Plus}><form className="space-y-4 p-5" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><Field label="الفرع"><Select defaultValue="branch-04"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{branches.map((branch) => <SelectItem key={branch.id} value={branch.id}>{branch.name}</SelectItem>)}</SelectContent></Select></Field><Field label="التصنيف"><Select defaultValue="cctv"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cctv">كاميرات مراقبة</SelectItem><SelectItem value="network">شبكات</SelectItem><SelectItem value="access">تحكم دخول</SelectItem></SelectContent></Select></Field><Field label="عنوان المشكلة"><Input required placeholder="وصف مختصر وواضح" /></Field><Field label="التفاصيل"><Textarea required placeholder="اشرح المشكلة ومتى بدأت..." /></Field><Button className="w-full" type="submit"><Plus className="h-4 w-4" />إرسال البلاغ</Button>{sent && <p className="rounded-md bg-accent p-3 text-sm font-bold text-accent-foreground">تم إنشاء البلاغ HD-2026-000453 بنجاح.</p>}</form></Panel><Panel title="دليل الفروع"><div className="grid gap-3 p-5 md:grid-cols-2">{branches.map((branch) => <Link key={branch.id} to="/branches/$branchId" params={{ branchId: branch.id }} className="rounded-lg border border-border p-4 transition-colors hover:bg-surface"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-md bg-flow text-brand-ink"><Building2 className="h-5 w-5" /></span><span className="text-xs font-bold text-brand-green">نشط</span></div><h2 className="mt-4 font-bold">{branch.name}</h2><p className="mt-1 text-sm text-muted-foreground">مدير الفرع: {branch.manager}</p><div className="mt-4 flex justify-between border-t border-border pt-3 text-xs"><span>{branch.open} مفتوحة</span><span>{branch.closed} مغلقة</span><span>رضا {branch.satisfaction}</span></div></Link>)}</div></Panel></section></AppShell>; }