import { createFileRoute } from "@tanstack/react-router";
import { Bell, Bot, Save, Settings, ShieldCheck, Timer } from "lucide-react";
import { AppShell } from "@/components/helpdesk/app-shell";
import { Field, Panel, SectionHeading } from "@/components/helpdesk/ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
export const Route = createFileRoute("/settings")({ head: () => ({ meta: [{ title: "الإعدادات | وزير الحلو" }, { name: "description", content: "إعدادات نظام الدعم ومستويات الخدمة." }, { property: "og:title", content: "الإعدادات | وزير الحلو" }, { property: "og:description", content: "إعدادات نظام الدعم ومستويات الخدمة." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: SettingsPage });
function SettingsPage() { return <AppShell title="الإعدادات"><SectionHeading title="إعدادات النظام" description="تحكم في التنبيهات ومستويات الخدمة والصلاحيات" /><section className="grid gap-4 xl:grid-cols-2"><Panel title="مستوى الخدمة" icon={Timer}><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="زمن الاستجابة للحرج"><Input defaultValue="30 دقيقة" /></Field><Field label="زمن الحل للحرج"><Input defaultValue="4 ساعات" /></Field><Field label="زمن الاستجابة للعالي"><Input defaultValue="60 دقيقة" /></Field><Field label="زمن الحل للعالي"><Input defaultValue="8 ساعات" /></Field></div></Panel><Panel title="التنبيهات" icon={Bell}><div className="divide-y divide-border p-5"><SettingRow title="تنبيه اقتراب انتهاء SLA" icon={Timer} /><SettingRow title="تنبيه إسناد مهمة جديدة" icon={ShieldCheck} /><SettingRow title="اقتراحات المساعد الذكي" icon={Bot} /></div></Panel></section><div className="flex justify-end"><Button><Save className="h-4 w-4" />حفظ الإعدادات</Button></div></AppShell>; }
function SettingRow({ title, icon: Icon }: { title: string; icon: typeof Settings }) { return <div className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div className="flex items-center gap-3"><Icon className="h-5 w-5 text-brand-ink" /><span className="text-sm font-bold">{title}</span></div><Switch defaultChecked /></div>; }