import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowRight, Building2, CheckCircle2, Clock3, MessageSquareText, RotateCcw, UserRound, Wrench } from "lucide-react";
import { AppShell } from "@/components/helpdesk/app-shell";
import { Panel, Stat } from "@/components/helpdesk/ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ticketEvents, tickets } from "@/lib/helpdesk-data";

export const Route = createFileRoute("/tickets/$ticketId")({ loader: ({ params }) => { const ticket = tickets.find((item) => item.id === params.ticketId); if (!ticket) throw notFound(); return ticket; }, head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.id} | وزير الحلو` : "البلاغ غير موجود | وزير الحلو" }, { name: "description", content: loaderData?.title ?? "تفاصيل البلاغ غير متاحة." }, { property: "og:title", content: loaderData ? `${loaderData.id} | وزير الحلو` : "البلاغ غير موجود" }, { property: "og:description", content: loaderData?.title ?? "تفاصيل البلاغ غير متاحة." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: TicketDetail });
function TicketDetail() { const ticket = Route.useLoaderData(); return <AppShell title="تفاصيل البلاغ"><div><Button asChild variant="ghost" size="sm"><Link to="/tickets"><ArrowRight className="h-4 w-4" />العودة للبلاغات</Link></Button><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="font-display text-2xl font-bold">{ticket.id}</h1><Badge>{ticket.status}</Badge></div><p className="mt-2 text-lg font-bold">{ticket.title}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline"><RotateCcw className="h-4 w-4" />إعادة فتح</Button><Button><CheckCircle2 className="h-4 w-4" />تعليم كمحلول</Button></div></div></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="الأولوية" value={ticket.priority} icon={Clock3} /><Stat label="الوقت المتبقي" value={ticket.sla} icon={Clock3} /><Stat label="الفرع" value={ticket.branch} icon={Building2} /><Stat label="الفني" value={ticket.technician} icon={UserRound} /></section><section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel title="بيانات البلاغ" icon={Wrench}><div className="space-y-5 p-5"><div><p className="text-xs font-bold text-muted-foreground">الوصف</p><p className="mt-2 text-sm leading-7">{ticket.description}</p></div><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">التصنيف</p><p className="mt-1 font-bold">{ticket.category}</p></div><div><p className="text-xs text-muted-foreground">الفني المسؤول</p><Link to="/technicians/$technicianId" params={{ technicianId: ticket.technicianId }} className="mt-1 block font-bold text-brand-ink">{ticket.technician}</Link></div><div><p className="text-xs text-muted-foreground">الفرع</p><Link to="/branches/$branchId" params={{ branchId: ticket.branchId }} className="mt-1 block font-bold text-brand-ink">{ticket.branch}</Link></div><div><p className="text-xs text-muted-foreground">الأصل المرتبط</p><p className="mt-1 font-bold">كاميرا CCTV-008</p></div></div></div></Panel><Panel title="سجل النشاط" icon={MessageSquareText}><div className="space-y-5 p-5">{ticketEvents.map((event) => <div key={event.time} className="grid grid-cols-[3rem_1fr] gap-3"><span className="font-mono text-xs font-bold text-brand-ink">{event.time}</span><div className="border-r-2 border-brand-green pr-3"><p className="text-sm font-bold">{event.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{event.text}</p></div></div>)}</div></Panel></section></AppShell>; }