/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as FieldServiceRouteImport } from './routes/field-service'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as BranchesBranchIdRouteImport } from './routes/branches.$branchId'
import { Route as TechniciansTechnicianIdRouteImport } from './routes/technicians.$technicianId'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldServiceRoute = FieldServiceRouteImport.update({
  id: '/field-service',
  path: '/field-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchIdRoute = BranchesBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => BranchesRoute,
} as any)
const TechniciansTechnicianIdRoute = TechniciansTechnicianIdRouteImport.update({
  id: '/$technicianId',
  path: '/$technicianId',
  getParentRoute: () => TechniciansRoute,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/branches': typeof BranchesRouteWithChildren
  '/field-service': typeof FieldServiceRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/branches': typeof BranchesRouteWithChildren
  '/field-service': typeof FieldServiceRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/branches': typeof BranchesRouteWithChildren
  '/field-service': typeof FieldServiceRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/branches'
    | '/field-service'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/branches'
    | '/field-service'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/branches'
    | '/field-service'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BranchesRoute: typeof BranchesRouteWithChildren
  FieldServiceRoute: typeof FieldServiceRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TechniciansRoute: typeof TechniciansRouteWithChildren
  TicketsRoute: typeof TicketsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-service': {
      id: '/field-service'
      path: '/field-service'
      fullPath: '/field-service'
      preLoaderRoute: typeof FieldServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchId': {
      id: '/branches/$branchId'
      path: '/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof BranchesBranchIdRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/technicians/$technicianId': {
      id: '/technicians/$technicianId'
      path: '/$technicianId'
      fullPath: '/technicians/$technicianId'
      preLoaderRoute: typeof TechniciansTechnicianIdRouteImport
      parentRoute: typeof TechniciansRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
  }
}

interface BranchesRouteChildren {
  BranchesBranchIdRoute: typeof BranchesBranchIdRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesBranchIdRoute: BranchesBranchIdRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

interface TechniciansRouteChildren {
  TechniciansTechnicianIdRoute: typeof TechniciansTechnicianIdRoute
}

const TechniciansRouteChildren: TechniciansRouteChildren = {
  TechniciansTechnicianIdRoute: TechniciansTechnicianIdRoute,
}

const TechniciansRouteWithChildren = TechniciansRoute._addFileChildren(
  TechniciansRouteChildren,
)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BranchesRoute: BranchesRouteWithChildren,
  FieldServiceRoute: FieldServiceRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TechniciansRoute: TechniciansRouteWithChildren,
  TicketsRoute: TicketsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
