/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as BranchesBranchIdRouteImport } from './routes/branches.$branchId'
import { Route as TechniciansTechnicianIdRouteImport } from './routes/technicians.$technicianId'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchIdRoute = BranchesBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => BranchesRoute,
} as any)
const TechniciansTechnicianIdRoute = TechniciansTechnicianIdRouteImport.update({
  id: '/$technicianId',
  path: '/$technicianId',
  getParentRoute: () => TechniciansRoute,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRouteWithChildren
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRouteWithChildren
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRouteWithChildren
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRouteWithChildren
  TechniciansRoute: typeof TechniciansRouteWithChildren
  TicketsRoute: typeof TicketsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchId': {
      id: '/branches/$branchId'
      path: '/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof BranchesBranchIdRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/technicians/$technicianId': {
      id: '/technicians/$technicianId'
      path: '/$technicianId'
      fullPath: '/technicians/$technicianId'
      preLoaderRoute: typeof TechniciansTechnicianIdRouteImport
      parentRoute: typeof TechniciansRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
  }
}

interface BranchesRouteChildren {
  BranchesBranchIdRoute: typeof BranchesBranchIdRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesBranchIdRoute: BranchesBranchIdRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

interface TechniciansRouteChildren {
  TechniciansTechnicianIdRoute: typeof TechniciansTechnicianIdRoute
}

const TechniciansRouteChildren: TechniciansRouteChildren = {
  TechniciansTechnicianIdRoute: TechniciansTechnicianIdRoute,
}

const TechniciansRouteWithChildren = TechniciansRoute._addFileChildren(
  TechniciansRouteChildren,
)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRouteWithChildren,
  TechniciansRoute: TechniciansRouteWithChildren,
  TicketsRoute: TicketsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
