/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BranchChatRouteImport } from './routes/branch-chat'
import { Route as BranchPanelRouteImport } from './routes/branch-panel'
import { Route as BranchStaffRouteImport } from './routes/branch-staff'
import { Route as BranchTasksRouteImport } from './routes/branch-tasks'
import { Route as BranchTicketsRouteImport } from './routes/branch-tickets'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as FieldServiceRouteImport } from './routes/field-service'
import { Route as HrPanelRouteImport } from './routes/hr-panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TechChatRouteImport } from './routes/tech-chat'
import { Route as TechPanelRouteImport } from './routes/tech-panel'
import { Route as TechProfileRouteImport } from './routes/tech-profile'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as BranchesBranchIdRouteImport } from './routes/branches.$branchId'
import { Route as TechniciansIndexRouteImport } from './routes/technicians.index'
import { Route as TechniciansTechnicianIdRouteImport } from './routes/technicians.$technicianId'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchChatRoute = BranchChatRouteImport.update({
  id: '/branch-chat',
  path: '/branch-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchPanelRoute = BranchPanelRouteImport.update({
  id: '/branch-panel',
  path: '/branch-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchStaffRoute = BranchStaffRouteImport.update({
  id: '/branch-staff',
  path: '/branch-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchTasksRoute = BranchTasksRouteImport.update({
  id: '/branch-tasks',
  path: '/branch-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchTicketsRoute = BranchTicketsRouteImport.update({
  id: '/branch-tickets',
  path: '/branch-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldServiceRoute = FieldServiceRouteImport.update({
  id: '/field-service',
  path: '/field-service',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPanelRoute = HrPanelRouteImport.update({
  id: '/hr-panel',
  path: '/hr-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TechChatRoute = TechChatRouteImport.update({
  id: '/tech-chat',
  path: '/tech-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TechPanelRoute = TechPanelRouteImport.update({
  id: '/tech-panel',
  path: '/tech-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const TechProfileRoute = TechProfileRouteImport.update({
  id: '/tech-profile',
  path: '/tech-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BranchesRoute,
} as any)
const BranchesBranchIdRoute = BranchesBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => BranchesRoute,
} as any)
const TechniciansIndexRoute = TechniciansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechniciansRoute,
} as any)
const TechniciansTechnicianIdRoute = TechniciansTechnicianIdRouteImport.update({
  id: '/$technicianId',
  path: '/$technicianId',
  getParentRoute: () => TechniciansRoute,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/branch-chat': typeof BranchChatRoute
  '/branch-panel': typeof BranchPanelRoute
  '/branch-staff': typeof BranchStaffRoute
  '/branch-tasks': typeof BranchTasksRoute
  '/branch-tickets': typeof BranchTicketsRoute
  '/branches': typeof BranchesRouteWithChildren
  '/chat': typeof ChatRoute
  '/directory': typeof DirectoryRoute
  '/field-service': typeof FieldServiceRoute
  '/hr-panel': typeof HrPanelRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tech-chat': typeof TechChatRoute
  '/tech-panel': typeof TechPanelRoute
  '/tech-profile': typeof TechProfileRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/branches/': typeof BranchesIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/branch-chat': typeof BranchChatRoute
  '/branch-panel': typeof BranchPanelRoute
  '/branch-staff': typeof BranchStaffRoute
  '/branch-tasks': typeof BranchTasksRoute
  '/branch-tickets': typeof BranchTicketsRoute
  '/chat': typeof ChatRoute
  '/directory': typeof DirectoryRoute
  '/field-service': typeof FieldServiceRoute
  '/hr-panel': typeof HrPanelRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tech-chat': typeof TechChatRoute
  '/tech-panel': typeof TechPanelRoute
  '/tech-profile': typeof TechProfileRoute
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/branches': typeof BranchesIndexRoute
  '/technicians': typeof TechniciansIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/branch-chat': typeof BranchChatRoute
  '/branch-panel': typeof BranchPanelRoute
  '/branch-staff': typeof BranchStaffRoute
  '/branch-tasks': typeof BranchTasksRoute
  '/branch-tickets': typeof BranchTicketsRoute
  '/branches': typeof BranchesRouteWithChildren
  '/chat': typeof ChatRoute
  '/directory': typeof DirectoryRoute
  '/field-service': typeof FieldServiceRoute
  '/hr-panel': typeof HrPanelRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/tech-chat': typeof TechChatRoute
  '/tech-panel': typeof TechPanelRoute
  '/tech-profile': typeof TechProfileRoute
  '/technicians': typeof TechniciansRouteWithChildren
  '/tickets': typeof TicketsRouteWithChildren
  '/branches/$branchId': typeof BranchesBranchIdRoute
  '/technicians/$technicianId': typeof TechniciansTechnicianIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/branches/': typeof BranchesIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/branch-chat'
    | '/branch-panel'
    | '/branch-staff'
    | '/branch-tasks'
    | '/branch-tickets'
    | '/branches'
    | '/chat'
    | '/directory'
    | '/field-service'
    | '/hr-panel'
    | '/login'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/tech-chat'
    | '/tech-panel'
    | '/tech-profile'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
    | '/branches/'
    | '/technicians/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/branch-chat'
    | '/branch-panel'
    | '/branch-staff'
    | '/branch-tasks'
    | '/branch-tickets'
    | '/chat'
    | '/directory'
    | '/field-service'
    | '/hr-panel'
    | '/login'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/tech-chat'
    | '/tech-panel'
    | '/tech-profile'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
    | '/branches'
    | '/technicians'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/branch-chat'
    | '/branch-panel'
    | '/branch-staff'
    | '/branch-tasks'
    | '/branch-tickets'
    | '/branches'
    | '/chat'
    | '/directory'
    | '/field-service'
    | '/hr-panel'
    | '/login'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/tech-chat'
    | '/tech-panel'
    | '/tech-profile'
    | '/technicians'
    | '/tickets'
    | '/branches/$branchId'
    | '/technicians/$technicianId'
    | '/tickets/$ticketId'
    | '/branches/'
    | '/technicians/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BranchChatRoute: typeof BranchChatRoute
  BranchPanelRoute: typeof BranchPanelRoute
  BranchStaffRoute: typeof BranchStaffRoute
  BranchTasksRoute: typeof BranchTasksRoute
  BranchTicketsRoute: typeof BranchTicketsRoute
  BranchesRoute: typeof BranchesRouteWithChildren
  ChatRoute: typeof ChatRoute
  DirectoryRoute: typeof DirectoryRoute
  FieldServiceRoute: typeof FieldServiceRoute
  HrPanelRoute: typeof HrPanelRoute
  LoginRoute: typeof LoginRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TechChatRoute: typeof TechChatRoute
  TechPanelRoute: typeof TechPanelRoute
  TechProfileRoute: typeof TechProfileRoute
  TechniciansRoute: typeof TechniciansRouteWithChildren
  TicketsRoute: typeof TicketsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-chat': {
      id: '/branch-chat'
      path: '/branch-chat'
      fullPath: '/branch-chat'
      preLoaderRoute: typeof BranchChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-panel': {
      id: '/branch-panel'
      path: '/branch-panel'
      fullPath: '/branch-panel'
      preLoaderRoute: typeof BranchPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-staff': {
      id: '/branch-staff'
      path: '/branch-staff'
      fullPath: '/branch-staff'
      preLoaderRoute: typeof BranchStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-tasks': {
      id: '/branch-tasks'
      path: '/branch-tasks'
      fullPath: '/branch-tasks'
      preLoaderRoute: typeof BranchTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-tickets': {
      id: '/branch-tickets'
      path: '/branch-tickets'
      fullPath: '/branch-tickets'
      preLoaderRoute: typeof BranchTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-service': {
      id: '/field-service'
      path: '/field-service'
      fullPath: '/field-service'
      preLoaderRoute: typeof FieldServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-panel': {
      id: '/hr-panel'
      path: '/hr-panel'
      fullPath: '/hr-panel'
      preLoaderRoute: typeof HrPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-chat': {
      id: '/tech-chat'
      path: '/tech-chat'
      fullPath: '/tech-chat'
      preLoaderRoute: typeof TechChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-panel': {
      id: '/tech-panel'
      path: '/tech-panel'
      fullPath: '/tech-panel'
      preLoaderRoute: typeof TechPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-profile': {
      id: '/tech-profile'
      path: '/tech-profile'
      fullPath: '/tech-profile'
      preLoaderRoute: typeof TechProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/branches/$branchId': {
      id: '/branches/$branchId'
      path: '/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof BranchesBranchIdRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/technicians/': {
      id: '/technicians/'
      path: '/'
      fullPath: '/technicians/'
      preLoaderRoute: typeof TechniciansIndexRouteImport
      parentRoute: typeof TechniciansRoute
    }
    '/technicians/$technicianId': {
      id: '/technicians/$technicianId'
      path: '/$technicianId'
      fullPath: '/technicians/$technicianId'
      preLoaderRoute: typeof TechniciansTechnicianIdRouteImport
      parentRoute: typeof TechniciansRoute
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
  }
}

interface BranchesRouteChildren {
  BranchesBranchIdRoute: typeof BranchesBranchIdRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesBranchIdRoute: BranchesBranchIdRoute,
  BranchesIndexRoute: BranchesIndexRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

interface TechniciansRouteChildren {
  TechniciansTechnicianIdRoute: typeof TechniciansTechnicianIdRoute
  TechniciansIndexRoute: typeof TechniciansIndexRoute
}

const TechniciansRouteChildren: TechniciansRouteChildren = {
  TechniciansTechnicianIdRoute: TechniciansTechnicianIdRoute,
  TechniciansIndexRoute: TechniciansIndexRoute,
}

const TechniciansRouteWithChildren = TechniciansRoute._addFileChildren(
  TechniciansRouteChildren,
)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BranchChatRoute: BranchChatRoute,
  BranchPanelRoute: BranchPanelRoute,
  BranchStaffRoute: BranchStaffRoute,
  BranchTasksRoute: BranchTasksRoute,
  BranchTicketsRoute: BranchTicketsRoute,
  BranchesRoute: BranchesRouteWithChildren,
  ChatRoute: ChatRoute,
  DirectoryRoute: DirectoryRoute,
  FieldServiceRoute: FieldServiceRoute,
  HrPanelRoute: HrPanelRoute,
  LoginRoute: LoginRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TechChatRoute: TechChatRoute,
  TechPanelRoute: TechPanelRoute,
  TechProfileRoute: TechProfileRoute,
  TechniciansRoute: TechniciansRouteWithChildren,
  TicketsRoute: TicketsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
